version: '2'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  node:
    image: node:10.9.0
    volumes:
      - ./ui:/opt/project
      - dependency-cache:/opt/project/node_modules
    working_dir: /opt/project
    entrypoint: ["npm"]

  # -------------------------------------------------------------------------- #

  ui-test:
    extends: node
    command: ["test"]

  # -------------------------------------------------------------------------- #

  ui-install-dependencies:
    extends: node
    command: ["i"]

  # -------------------------------------------------------------------------- #

  ui-build:
    extends: node
    command: ["run", "build"]

  # -------------------------------------------------------------------------- #

  server-mock:
    extends: node
    ports:
      - "4000:4000"
    entrypoint: node
    command: ["/opt/project/mock/index.js"]

  # -------------------------------------------------------------------------- #

  ui-development:
    tty: true
    extends: node
    ports:
      - "3000:3000"
    depends_on:
      - server-mock
    command: ["run", "devserver"]

  # -------------------------------------------------------------------------- #

  ui-production:
    tty: true
    extends: node
    ports:
      - "3000:3000"
    depends_on:
      - server-production
    command: ["run", "prodserver"]

  # -------------------------------------------------------------------------- #

  server-production:
    image: openbank/demo
    build: .
    ports:
      - "8080:8080"
      - "4400:4400"
      - "4401:4401"
      - "4001:4001"
      - "4002:4002"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/openbank:/data
      - ./data/mongo:/var/lib/mongodb
      - ./secrets:/openbank/secrets

# ---------------------------------------------------------------------------- #

volumes:
  dependency-cache:
