version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  node: &node
    image: node:10.9.0
    volumes: &node_volumes
      - ./ui:/opt/project
      - dependency-cache:/opt/project/node_modules
    working_dir: /opt/project
    entrypoint: ["npm"]

  # -------------------------------------------------------------------------- #

  ui-test:
    <<: *node
    command: ["test"]

  # -------------------------------------------------------------------------- #

  ui-install-dependencies:
    <<: *node
    command: ["i"]

  # -------------------------------------------------------------------------- #

  ui-build:
    <<: *node
    command: ["run", "build"]

  # -------------------------------------------------------------------------- #

  server-mock:
    <<: *node
    ports:
      - "4000:4000"
    networks:
      - overlay
    entrypoint: node
    command: ["/opt/project/mock/index.js"]

  # -------------------------------------------------------------------------- #

  ui-development:
    tty: true
    <<: *node
    ports:
      - "3000:3000"
    networks:
      - overlay
    depends_on:
      - server-mock
    command: ["run", "devserver"]

  # -------------------------------------------------------------------------- #

  ui-production:
    tty: true
    <<: *node
    ports:
      - "3000:3000"
    depends_on:
      - server-production
    command: ["run", "prodserver"]

  # -------------------------------------------------------------------------- #

  server-production:
    image: openbank/demo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LAKE_VERSION: 1.1.9
        VAULT_VERSION: 1.2.9
        LEDGER_VERSION: 1.0.4
        FIO_BCO_VERSION: 1.2.6
        BONDSTER_BCO_VERSION: 1.2.7
        CNB_RATES_VERSION: 1.0.1
        SEARCH_VERSION: 1.2.6
    ports:
      - "8080:8080"
      - "4400:4400"
      - "4401:4401"
      - "4001:4001"
      - "4002:4002"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/openbank:/data
      - ./data/mongo:/var/lib/mongodb
      - ./secrets:/openbank/secrets

# ---------------------------------------------------------------------------- #

volumes:
  dependency-cache:

networks:
  overlay:
