version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  node: &node
    image: node:10.9.0
    volumes: &node_volumes
      - ./ui:/opt/project
      - dependency-cache:/opt/project/node_modules
    working_dir: /opt/project
    entrypoint: ["npm"]

  # -------------------------------------------------------------------------- #

  ui-test:
    <<: *node
    command: ["test"]

  # -------------------------------------------------------------------------- #

  ui-install-dependencies:
    <<: *node
    command: ["install"]

  # -------------------------------------------------------------------------- #

  ui-build:
    <<: *node
    command: ["run", "build"]

  # -------------------------------------------------------------------------- #

  server-mock:
    image: node:10.9.0
    volumes:
      - ./ui/mock:/opt/project/mock
      - dependency-cache:/opt/project/node_modules
    hostname: server-mock
    working_dir: /opt/project/mock
    ports:
      - "4000:4000"
    entrypoint: node
    command: ["/opt/project/node_modules/nodemon/bin/nodemon.js", "/opt/project/mock/index.js"]

  # -------------------------------------------------------------------------- #

  ui-development:
    <<: *node
    ports:
      - "3000:3000"
    depends_on:
      - server-mock
    command: ["run", "devserver"]

  # -------------------------------------------------------------------------- #

  postgres:
    image: openbak/postgres
    hostname: postgres
    build: postgres
    volumes:
      - openbank-secondary:/var/lib/postgresql/data

  # -------------------------------------------------------------------------- #

  demo:
    image: openbank/demo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LAKE_VERSION: 1.2.3
        VAULT_VERSION: 1.3.1
        LEDGER_VERSION: 1.1.1
        FIO_BCO_VERSION: 1.2.9
        BONDSTER_BCO_VERSION: 1.2.10
        DWH_VERSION: 0.0.0
    ports:
      - "443:443"
      - "8443:8443"
      - "4400:4400"
      - "4401:4401"
      - "4001:4001"
      - "4002:4002"
    links:
      - postgres
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - openbank-primary:/data
      - ./secrets:/openbank/secrets
      - ./ui/build:/var/www

# ---------------------------------------------------------------------------- #

volumes:
  openbank-primary:
  openbank-secondary:
  dependency-cache:
