version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  postgres:
    image: openbank/postgres:${ARCH}-0.0.0.main
    hostname: postgres
    restart: on-failure
    volumes:
      - openbank-secondary:/var/lib/postgresql/data

  # -------------------------------------------------------------------------- #

  metrics:
    image: openbank/metrics:v0.0.0-main
    hostname: metrics
    restart: on-failure
    volumes:
      - openbank-metrics:/opt/metrics/data

  # -------------------------------------------------------------------------- #

  demo:
    image: openbank/demo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARCH: ${ARCH}
        LAKE_VERSION: 1.3.0
        VAULT_VERSION: 1.3.4
        LEDGER_VERSION: 1.1.4
        FIO_BCO_VERSION: 1.3.2
        BONDSTER_BCO_VERSION: 1.3.2
        DWH_VERSION: 1.1.1
    ports:
      - "443:443"
      - "8443:8443"
      - "4400:4400"
      - "4401:4401"
      - "4001:4001"
      - "4002:4002"
    links:
      - postgres
      - metrics
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - openbank-primary:/data

# ---------------------------------------------------------------------------- #

volumes:
  openbank-primary:
  openbank-secondary:
  openbank-metrics:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/report/metrics
