// FIXME dedup
export const APP_UNMOUNT = 'APP_UNMOUNT'

export const TOKENS_API_REQUEST_INIT = 'BONDSTER_TOKENS_API_REQUEST_INIT'
export const TOKENS_API_REQUEST_SUCCESS = 'BONDSTER_TOKENS_API_REQUEST_SUCCESS'
export const TOKENS_API_REQUEST_FAILURE = 'BONDSTER_TOKENS_API_REQUEST_FAILURE'

export const CREATE_TOKEN_API_REQUEST_SUCCESS = 'BONDSTER_CREATE_TOKEN_API_REQUEST_SUCCESS'
