version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  metrics:
    image: openbank/metrics:${ARCH}-1.0.0.main
    volumes:
      - ./metrics:/opt/metrics/data
    expose:
      - 8125/udp

  # -------------------------------------------------------------------------- #

  lake:
    image: openbank/lake:${ARCH}-1.3.0.main
    environment:
      LAKE_LOG_LEVEL: DEBUG
      LAKE_PORT_PULL: 5562
      LAKE_PORT_PUB: 5561
      LAKE_STATSD_ENDPOINT: metrics:8125
    expose:
      - 5562/tcp
      - 5561/tcp
    links:
      - metrics
    entrypoint:
      - lake

  # -------------------------------------------------------------------------- #

  ledger-rest:
    image: openbank/ledger:${ARCH}-1.1.4.main
    environment:
      LEDGER_STORAGE: /data
      LEDGER_LOG_LEVEL: DEBUG
      LEDGER_HTTP_PORT: 443
      LEDGER_SERVER_KEY: /run/secrets/http_ledger_key
      LEDGER_SERVER_CERT: /run/secrets/http_ledger_crt
      LEDGER_LAKE_HOSTNAME: lake
      LEDGER_TRANSACTION_INTEGRITY_SCANINTERVAL: 5m
      LEDGER_MEMORY_THRESHOLD: 0
      LEDGER_STORAGE_THRESHOLD: 0
      LEDGER_STATSD_ENDPOINT: metrics:8125
    volumes:
      - ./data:/data
    secrets:
      - http_ledger_key
      - http_ledger_crt
    ports:
      - 5200:443/tcp
    links:
      - lake
      - metrics
    entrypoint:
      - ledger-rest

  # -------------------------------------------------------------------------- #

  ledger-unit:
    image: openbank/ledger:${ARCH}-1.1.4.main
    environment:
      LEDGER_STORAGE: /data
      LEDGER_TENANT: test
      LEDGER_LOG_LEVEL: DEBUG
      LEDGER_LAKE_HOSTNAME: lake
      LEDGER_TRANSACTION_INTEGRITY_SCANINTERVAL: 5m
      LEDGER_MEMORY_THRESHOLD: 0
      LEDGER_STORAGE_THRESHOLD: 0
      LEDGER_STATSD_ENDPOINT: metrics:8125
    volumes:
      - ./data:/data
    links:
      - lake
      - metrics
    entrypoint:
      - ledger-unit

  # -------------------------------------------------------------------------- #

  vault-rest:
    image: openbank/vault:${ARCH}-1.3.5.main
    environment:
      VAULT_STORAGE: /data
      VAULT_LOG_LEVEL: DEBUG
      VAULT_SNAPSHOT_SATURATION_TRESHOLD: 100
      VAULT_HTTP_PORT: 443
      VAULT_SERVER_KEY: /run/secrets/http_vault_key
      VAULT_SERVER_CERT: /run/secrets/http_vault_crt
      VAULT_LAKE_HOSTNAME: lake
      VAULT_MEMORY_THRESHOLD: 0
      VAULT_STORAGE_THRESHOLD: 0
      VAULT_STATSD_ENDPOINT: metrics:8125
    volumes:
      - ./data:/data
    secrets:
      - http_vault_key
      - http_vault_crt
    ports:
      - 5100:443/tcp
    links:
      - lake
      - metrics
    entrypoint:
      - vault-rest

  # -------------------------------------------------------------------------- #

  vault-unit:
    image: openbank/vault:${ARCH}-1.3.5.main
    environment:
      VAULT_STORAGE: /data
      VAULT_TENANT: test
      VAULT_LOG_LEVEL: DEBUG
      VAULT_SNAPSHOT_SATURATION_TRESHOLD: 100
      VAULT_LAKE_HOSTNAME: lake
      VAULT_MEMORY_THRESHOLD: 0
      VAULT_STORAGE_THRESHOLD: 0
      VAULT_STATSD_ENDPOINT: metrics:8125
    volumes:
      - ./data:/data
    links:
      - lake
      - metrics
    entrypoint:
      - vault-unit

  # -------------------------------------------------------------------------- #

  fio-bco-rest:
    image: openbank/fio-bco:${ARCH}-1.3.3.main
    environment:
      FIO_BCO_STORAGE: /data
      FIO_BCO_TENANT: test
      FIO_BCO_LOG_LEVEL: DEBUG
      FIO_BCO_FIO_GATEWAY: https://www.fio.cz
      FIO_BCO_SYNC_RATE: 32s
      FIO_BCO_LAKE_HOSTNAME: lake
      FIO_BCO_HTTP_PORT: 443
      FIO_BCO_SERVER_KEY: /run/secrets/http_fio-bco_key
      FIO_BCO_SERVER_CERT: /run/secrets/http_fio-bco_crt
      FIO_BCO_ENCRYPTION_KEY: /run/secrets/fs_key
      FIO_BCO_MEMORY_THRESHOLD: 0
      FIO_BCO_STORAGE_THRESHOLD: 0
      FIO_BCO_STATSD_ENDPOINT: metrics:8125
    secrets:
      - http_fio-bco_key
      - http_fio-bco_crt
      - fs_key
    volumes:
      - ./data:/data
    ports:
      - 5300:443/tcp
    links:
      - lake
      - metrics
    entrypoint:
      - fio-bco-rest

  # -------------------------------------------------------------------------- #

  fio-bco-import:
    image: openbank/fio-bco:${ARCH}-1.3.3.main
    environment:
      FIO_BCO_STORAGE: /data
      FIO_BCO_TENANT: test
      FIO_BCO_LOG_LEVEL: DEBUG
      FIO_BCO_FIO_GATEWAY: https://www.fio.cz
      FIO_BCO_LEDGER_GATEWAY: https://ledger-rest
      FIO_BCO_VAULT_GATEWAY: https://vault-rest
      FIO_BCO_LAKE_HOSTNAME: lake
      FIO_BCO_ENCRYPTION_KEY: /run/secrets/fs_key
      FIO_BCO_MEMORY_THRESHOLD: 0
      FIO_BCO_STORAGE_THRESHOLD: 0
      FIO_BCO_STATSD_ENDPOINT: metrics:8125
    secrets:
      - fs_key
    volumes:
      - ./data:/data
      - ./secrets/openbank-ca.crt:/usr/local/share/ca-certificates/openbank-ca.crt:ro
    links:
      - lake
      - metrics
      - ledger-rest
      - vault-rest
    entrypoint: |
      /bin/bash -c "update-ca-certificates ; fio-bco-import"
  
  # -------------------------------------------------------------------------- #

  bondster-bco-rest:
    image: openbank/bondster-bco:${ARCH}-1.3.3.main
    environment:
      BONDSTER_BCO_STORAGE: /data
      BONDSTER_BCO_LOG_LEVEL: DEBUG
      BONDSTER_BCO_MEMORY_THRESHOLD: 0
      BONDSTER_BCO_STORAGE_THRESHOLD: 0
      BONDSTER_BCO_LAKE_HOSTNAME: lake
      BONDSTER_BCO_HTTP_PORT: 443
      BONDSTER_BCO_SERVER_KEY: /run/secrets/http_bondster-bco_key
      BONDSTER_BCO_SERVER_CERT: /run/secrets/http_bondster-bco_crt
      BONDSTER_BCO_ENCRYPTION_KEY: /run/secrets/fs_key
    secrets:
      - http_bondster-bco_key
      - http_bondster-bco_crt
      - fs_key
    volumes:
      - ./data:/data
    ports:
      - 5400:443/tcp
    entrypoint:
      - bondster-bco-rest

  # -------------------------------------------------------------------------- #

  bondster-bco-import:
    image: openbank/bondster-bco:${ARCH}-1.3.3.main
    environment:
      BONDSTER_BCO_STORAGE: /data
      BONDSTER_BCO_TENANT: test
      BONDSTER_BCO_LOG_LEVEL: DEBUG
      BONDSTER_BCO_SYNC_RATE: 1h
      BONDSTER_BCO_LEDGER_GATEWAY: https://ledger-rest
      BONDSTER_BCO_VAULT_GATEWAY: https://vault-rest
      BONDSTER_BCO_BONDSTER_GATEWAY: https://ib.bondster.com
      BONDSTER_BCO_LAKE_HOSTNAME: lake
      BONDSTER_BCO_ENCRYPTION_KEY: /run/secrets/fs_key
      BONDSTER_BCO_MEMORY_THRESHOLD: 0
      BONDSTER_BCO_STORAGE_THRESHOLD: 0
    secrets:
      - fs_key
    volumes:
      - ./data:/data
      - ./secrets/openbank-ca.crt:/usr/local/share/ca-certificates/openbank-ca.crt:ro
    links:
      - lake
      - metrics
      - ledger-rest
      - vault-rest
    entrypoint: |
      /bin/bash -c "update-ca-certificates ; bondster-bco-import"

  # -------------------------------------------------------------------------- #

  postgres:
    image: openbank/postgres:${ARCH}-0.0.0.main

  # -------------------------------------------------------------------------- #

  data-warehouse:
    image: openbank/data-warehouse:${ARCH}-1.1.1.main
    environment:
      DATA_WAREHOUSE_LOG_LEVEL: DEBUG
      DATA_WAREHOUSE_HTTP_PORT: 8080
      DATA_WAREHOUSE_PRIMARY_STORAGE_PATH: /data
      DATA_WAREHOUSE_POSTGRES_URL: jdbc:postgresql://postgres:5432/openbank
      DATA_WAREHOUSE_STATSD_URL: udp://metrics:8125
    volumes:
      - ./data:/data
    ports:
      - 5500:8080/tcp
    links:
      - postgres
      - metrics
    entrypoint:
      - data-warehouse

# ---------------------------------------------------------------------------- #

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

# ---------------------------------------------------------------------------- #

secrets:
  fs_key:
    file: ./secrets/fs.key
  http_vault_key:
    file: ./secrets/vault-rest.key
  http_vault_crt:
    file: ./secrets/vault-rest.crt
  http_ledger_key:
    file: ./secrets/ledger-rest.key
  http_ledger_crt:
    file: ./secrets/ledger-rest.crt
  http_fio-bco_key:
    file: ./secrets/fio-bco-rest.key
  http_fio-bco_crt:
    file: ./secrets/fio-bco-rest.crt
  http_bondster-bco_key:
    file: ./secrets/bondster-bco-rest.key
  http_bondster-bco_crt:
    file: ./secrets/bondster-bco-rest.crt

# ---------------------------------------------------------------------------- #
