export const APP_UNMOUNT = 'APP_UNMOUNT'

export const TOKENS_API_REQUEST_INIT = 'TOKENS_API_REQUEST_INIT'
export const TOKENS_API_REQUEST_SUCCESS = 'TOKENS_API_REQUEST_SUCCESS'
export const TOKENS_API_REQUEST_FAILURE = 'TOKENS_API_REQUEST_FAILURE'
