// FIXME dedup
export const APP_UNMOUNT = 'APP_UNMOUNT'

export const TOKENS_API_REQUEST_INIT = 'FIO_TOKENS_API_REQUEST_INIT'
export const TOKENS_API_REQUEST_SUCCESS = 'FIO_TOKENS_API_REQUEST_SUCCESS'
export const TOKENS_API_REQUEST_FAILURE = 'FIO_TOKENS_API_REQUEST_FAILURE'
