export const TENANTS_API_REQUEST_INIT = 'TENANTS_API_REQUEST_INIT'
export const TENANTS_API_REQUEST_SUCCESS = 'TENANTS_API_REQUEST_SUCCESS'
export const TENANTS_API_REQUEST_FAILURE = 'TENANTS_API_REQUEST_FAILURE'

export const TENANTS_CHANGE = 'TENANTS_CHANGE'

