export const ACCOUNTS_API_REQUEST_INIT = 'ACCOUNTS_API_REQUEST_INIT'
export const ACCOUNTS_API_REQUEST_SUCCESS = 'ACCOUNTS_API_REQUEST_SUCCESS'
export const ACCOUNTS_API_REQUEST_FAILURE = 'ACCOUNTS_API_REQUEST_FAILURE'

export const CREATE_ACCOUNT_API_REQUEST_SUCCESS = 'CREATE_ACCOUNT_API_REQUEST_SUCCESS'

export const TRANSACTIONS_API_REQUEST_INIT = 'TRANSACTIONS_API_REQUEST_INIT'
export const TRANSACTIONS_API_REQUEST_SUCCESS = 'TRANSACTIONS_API_REQUEST_SUCCESS'
export const TRANSACTIONS_API_REQUEST_FAILURE = 'TRANSACTIONS_API_REQUEST_FAILURE'
