// FIXME dedup
export const APP_UNMOUNT = 'APP_UNMOUNT'

export const ACCOUNTS_API_REQUEST_INIT = 'ACCOUNTS_API_REQUEST_INIT'
export const ACCOUNTS_API_REQUEST_SUCCESS = 'ACCOUNTS_API_REQUEST_SUCCESS'
export const ACCOUNTS_API_REQUEST_FAILURE = 'ACCOUNTS_API_REQUEST_FAILURE'

export const TRANSACTIONS_API_REQUEST_INIT = 'TRANSACTIONS_API_REQUEST_INIT'
export const TRANSACTIONS_API_REQUEST_SUCCESS = 'TRANSACTIONS_API_REQUEST_SUCCESS'
export const TRANSACTIONS_API_REQUEST_FAILURE = 'TRANSACTIONS_API_REQUEST_FAILURE'
